{% set name = "streamtracer" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/streamtracer-{{ version }}.tar.gz
  sha256: b932226293e7ddcac025f2d3204dbb95ec391850e435d97c137f765430cacc06

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [py<310]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - maturin >=1.0,<2.0                     # [build_platform != target_platform]
  host:
    - python
    - pip
    - maturin >=1.0,<2.0
  run:
    - python
    - packaging
    - numpy >=1.23

test:
  imports:
    - streamtracer
  commands:
    - pip check
    - pytest --pyargs streamtracer
  requires:
    - pip
    - pytest
    - pytest-doctestplus

about:
  home: https://streamtracer.readthedocs.io/en/latest/
  summary: Fast streamline tracing in python
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - STBadman
    - cadair
    - jgieseler
