{% set name = "streamtracer" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/streamtracer-{{ version }}.tar.gz
  sha256: 29955653f88970ab3b1fe3e9c470e3b243c1a04e157647d22b2b13494f8864ca

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  skip: true  # [py<37]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - python
    - setuptools >=45
    - setuptools-scm >=6.2
    - numpy
    - maturin >=0.13,<0.14
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - streamtracer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://streamtracer.readthedocs.io/en/latest/
  summary: Fast streamline tracing in python
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jgieseler
