{% set name = "streamtracer" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/streamtracer-{{ version }}.tar.gz
  sha256: 3dda22590b85f922eee74ae7fdb9703332a129364edf1593239ba971a73a27d1

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  skip: true  # [py<310]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - python
    - pip
    - maturin >=1.0,<2.0
  run:
    - python
    - packaging
    - numpy >=1.23

test:
  imports:
    - streamtracer
  commands:
    - pip check
    - pytest --pyargs streamtracer
  requires:
    - pip
    - pytest
    - pytest-doctestplus

about:
  home: https://streamtracer.readthedocs.io/en/latest/
  summary: Fast streamline tracing in python
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - STBadman
    - cadair
    - jgieseler
