{% set name = "streamtracer" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/streamtracer-{{ version }}.tar.gz
  sha256: be0e477e680822311b14b509964156208494278b4e12c8921f336ba4082bc3c9

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [py<310]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - maturin >=1.0,<2.0                     # [build_platform != target_platform]
  host:
    - python
    - pip
    - maturin >=1.0,<2.0
  run:
    - python
    - packaging
    - numpy >=1.23

test:
  imports:
    - streamtracer
  commands:
    - pip check
    - pytest --pyargs streamtracer
  requires:
    - pip
    - pytest
    - pytest-doctestplus

about:
  home: https://streamtracer.readthedocs.io/en/latest/
  summary: Fast streamline tracing in python
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - STBadman
    - cadair
    - jgieseler
